ECHO OFF
CLS
ECHO.
git tag > tag.log
For /F "UseBackQ Delims==" %%A In ("tag.log") Do Set "TAG=%%A"
IF %TAG%=="" exit 0;
echo GIT TAG VERSION :%TAG%
rem del tag.log

echo ; Script generated by the HM NIS Edit Script Wizard. > installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; HM NIS Edit Wizard helper defines >> installer.build.%TAG%.nsi
echo !define PRODUCT_NAME "CoreTracker" >> installer.build.%TAG%.nsi
echo !define PRODUCT_VERSION "%TAG%" >> installer.build.%TAG%.nsi
echo !define PRODUCT_PUBLISHER "helloFhwang, Inc." >> installer.build.%TAG%.nsi
echo !define PRODUCT_WEB_SITE "https://github.com/Fhwang0926/CoreTracker" >> installer.build.%TAG%.nsi
echo !define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo !define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" >> installer.build.%TAG%.nsi
echo !define PRODUCT_UNINST_ROOT_KEY "HKLM" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; MUI 1.67 compatible ------ >> installer.build.%TAG%.nsi
echo !include "MUI.nsh" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; MUI Settings >> installer.build.%TAG%.nsi
echo !define MUI_ABORTWARNING >> installer.build.%TAG%.nsi
echo !define MUI_ICON "..\Properties\icon\form.ico" >> installer.build.%TAG%.nsi
echo !define MUI_UNICON "..\Properties\icon\form.ico" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; Language Selection Dialog Settings >> installer.build.%TAG%.nsi
echo !define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}" >> installer.build.%TAG%.nsi
echo !define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}" >> installer.build.%TAG%.nsi
echo !define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; Welcome page >> installer.build.%TAG%.nsi
echo !insertmacro MUI_PAGE_WELCOME >> installer.build.%TAG%.nsi

echo ; License page >> installer.build.%TAG%.nsi
echo !insertmacro MUI_PAGE_LICENSE "..\License" >> installer.build.%TAG%.nsi

echo !define MUI_PAGE_CUSTOMFUNCTION_SHOW RestrictDirPage >> installer.build.%TAG%.nsi
echo ; Directory page  >> installer.build.%TAG%.nsi
echo !insertmacro MUI_PAGE_DIRECTORY >> installer.build.%TAG%.nsi
echo.  >> installer.build.%TAG%.nsi
echo !insertmacro MUI_PAGE_INSTFILES >> installer.build.%TAG%.nsi
echo.  >> installer.build.%TAG%.nsi
echo Function RestrictDirPage >> installer.build.%TAG%.nsi
echo  !if "${MUI_SYSVERSION}" >= 2.0 >> installer.build.%TAG%.nsi
echo    SendMessage $mui.DirectoryPage.Directory ${EM_SETREADONLY} 1 0 >> installer.build.%TAG%.nsi
echo    EnableWindow $mui.DirectoryPage.BrowseButton 0 >> installer.build.%TAG%.nsi
echo  !else >> installer.build.%TAG%.nsi
echo    FindWindow $0 '#32770' '' $HWNDPARENT >> installer.build.%TAG%.nsi
echo    GetDlgItem $1 $0 0x3FB >> installer.build.%TAG%.nsi
echo    SendMessage $1 ${EM_SETREADONLY} 1 0 >> installer.build.%TAG%.nsi
echo    GetDlgItem $1 $0 0x3E9 >> installer.build.%TAG%.nsi
echo    EnableWindow $1 0 >> installer.build.%TAG%.nsi
echo  !endif >> installer.build.%TAG%.nsi
echo FunctionEnd >> installer.build.%TAG%.nsi

echo ; Finish page >> installer.build.%TAG%.nsi
echo !define MUI_FINISHPAGE_RUN "$INSTDIR\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo ;!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\README.md" >> installer.build.%TAG%.nsi
echo !insertmacro MUI_PAGE_FINISH >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; Uninstaller pages >> installer.build.%TAG%.nsi
echo !insertmacro MUI_UNPAGE_INSTFILES >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; Language files >> installer.build.%TAG%.nsi
echo !insertmacro MUI_LANGUAGE "English" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo ; MUI end ------ >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo Name "${PRODUCT_NAME} ${PRODUCT_VERSION}" >> installer.build.%TAG%.nsi
echo OutFile "CoreTracker_installer.exe" >> installer.build.%TAG%.nsi
echo InstallDir "$PROGRAMFILES\CoreTracker" >> installer.build.%TAG%.nsi
echo InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" "" >> installer.build.%TAG%.nsi
echo ShowInstDetails show >> installer.build.%TAG%.nsi
echo ShowUnInstDetails show >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo Function .onInit >> installer.build.%TAG%.nsi
echo   !insertmacro MUI_LANGDLL_DISPLAY >> installer.build.%TAG%.nsi
echo FunctionEnd >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo Section "MainSection" SEC01 >> installer.build.%TAG%.nsi
echo   SetOutPath "$INSTDIR" >> installer.build.%TAG%.nsi
echo   SetOverwrite ifnewer >> installer.build.%TAG%.nsi
echo   File "..\bin\Release\x64\Newtonsoft.Json.dll" >> installer.build.%TAG%.nsi
echo   File "..\bin\Release\x64\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo   File "..\bin\CoreTrackerHelper\CoreTrackerHelper.exe" >> installer.build.%TAG%.nsi
echo   File "..\bin\CoreTrackerHelper\CoreTrackerHelper.dll" >> installer.build.%TAG%.nsi
echo   File "_install.bat" >> installer.build.%TAG%.nsi
echo   File "_uninstall.bat" >> installer.build.%TAG%.nsi
echo   File "..\README.md" >> installer.build.%TAG%.nsi
echo   ExecWait "$INSTDIR\_install.bat $INSTDIR\${PRODUCT_NAME}Helper.exe" >> installer.build.%TAG%.nsi
echo   CreateDirectory "$SMPROGRAMS\CoreTracker" >> installer.build.%TAG%.nsi
echo   CreateShortCut "$SMPROGRAMS\CoreTracker\CoreTracker.lnk" "$INSTDIR\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo   CreateShortCut "$DESKTOP\CoreTracker.lnk" "$INSTDIR\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo SectionEnd >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo Section -AdditionalIcons >> installer.build.%TAG%.nsi
echo   WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}" >> installer.build.%TAG%.nsi
echo   CreateShortCut "$SMPROGRAMS\CoreTracker\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url" >> installer.build.%TAG%.nsi
echo   CreateShortCut "$SMPROGRAMS\CoreTracker\Uninstall.lnk" "$INSTDIR\uninst.exe" >> installer.build.%TAG%.nsi
echo SectionEnd >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo Section -Post >> installer.build.%TAG%.nsi
echo   WriteUninstaller "$INSTDIR\uninst.exe" >> installer.build.%TAG%.nsi
echo   WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)" >> installer.build.%TAG%.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe" >> installer.build.%TAG%.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}" >> installer.build.%TAG%.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}" >> installer.build.%TAG%.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}" >> installer.build.%TAG%.nsi

echo SectionEnd >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi
echo Function un.onUninstSuccess >> installer.build.%TAG%.nsi
echo   HideWindow >> installer.build.%TAG%.nsi
echo   MessageBox MB_ICONINFORMATION^|MB_OK "$(^Name) was successfully removed from your computer." >> installer.build.%TAG%.nsi
echo FunctionEnd >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi
echo Function un.onInit >> installer.build.%TAG%.nsi
echo !insertmacro MUI_UNGETLANGUAGE >> installer.build.%TAG%.nsi
echo   MessageBox MB_ICONQUESTION^|MB_YESNO^|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2 >> installer.build.%TAG%.nsi
echo   Abort >> installer.build.%TAG%.nsi
echo FunctionEnd >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi

echo Section Uninstall >> installer.build.%TAG%.nsi
echo   ExecWait "$INSTDIR\_uninstall.bat" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\${PRODUCT_NAME}.url" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\uninst.exe" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\README.md" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\_install.bat" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\_uninstall.bat" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\CoreTracker.exe" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\CoreTrackerHelper.exe" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\CoreTrackerHelper.dll" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\Newtonsoft.Json.dll" >> installer.build.%TAG%.nsi
echo   Delete "$INSTDIR\NULL" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi
echo   Delete "$SMPROGRAMS\CoreTracker\Uninstall.lnk" >> installer.build.%TAG%.nsi
echo   Delete "$SMPROGRAMS\CoreTracker\Website.lnk" >> installer.build.%TAG%.nsi
echo   Delete "$DESKTOP\CoreTracker.lnk" >> installer.build.%TAG%.nsi
echo   Delete "$SMPROGRAMS\CoreTracker\CoreTracker.lnk" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi
echo   RMDir "$SMPROGRAMS\CoreTracker" >> installer.build.%TAG%.nsi
echo   RMDir "$INSTDIR" >> installer.build.%TAG%.nsi
echo. >> installer.build.%TAG%.nsi
echo   DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" >> installer.build.%TAG%.nsi
echo   DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}" >> installer.build.%TAG%.nsi
echo   SetAutoClose true >> installer.build.%TAG%.nsi

echo SectionEnd >> installer.build.%TAG%.nsi
echo %TAG% Done!
echo off
code installer.build.%TAG%.nsi